spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/locationpro?characterEncoding=utf8&amp;useSSL=false
        username: root
        password: oracle
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      cache: false
      mode: HTML5
      content-type: text/html
      encoding: UTF-8
mybatis:
#  mapper-locations: classpath:com.ll.location.dao
  type-aliases-package: com.ll.location.model
